### ISSUE TITLE
Непонятное исключение

### ISSUE THREAD

**Issue by AlphaBeth** [nymphaea-v1/Lab5#6]
При вводе ctrl+d

```java -jar Lab5.jar 
Picked up _JAVA_OPTIONS: -Xmx128M -Xms128M
File is empty
Exception in thread "main" java.util.NoSuchElementException: No line found
        at java.util.Scanner.nextLine(Scanner.java:1540)
        at lab5.InputReader.startReading(InputReader.java:34)
        at lab5.Main.main(Main.java:11)
```

**Comment by nymphaea-v1** [comment]
https://github.com/nymphaea-v1/Lab5/commit/e203c9421e7425e8d1a5e2ce6cdccd769522de59
